name: Run Discord Bot

on:
  workflow_dispatch:  # Manual trigger
  push:               # Run on code changes
    branches: [ main, master ]
  schedule:           # Restart every 5 hours
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # 5 hours 50 minutes
    
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord.py motor python-dotenv pymongo
        
    - name: Wait for MongoDB
      run: |
        echo "Waiting for MongoDB to be ready..."
        sleep 10
        echo "MongoDB should be ready now!"
        
    - name: Run Discord Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        echo "=== Starting Discord Bot ==="
        echo "Python version: $(python --version)"
        
        # Simple restart loop
        MAX_RESTARTS=5
        RESTART_COUNT=0
        
        while [ $RESTART_COUNT -le $MAX_RESTARTS ]; do
          echo "Starting bot (attempt $((RESTART_COUNT + 1)))"
          
          python main.py
          EXIT_CODE=$?
          
          if [ $EXIT_CODE -eq 0 ]; then
            echo "Bot stopped normally"
            break
          else
            echo "Bot stopped with error code $EXIT_CODE"
            RESTART_COUNT=$((RESTART_COUNT + 1))
            
            if [ $RESTART_COUNT -gt $MAX_RESTARTS ]; then
              echo "Max restart attempts reached"
              exit 1
            fi
            
            echo "Restarting in 5 seconds..."
            sleep 5
          fi
        done
