name: Run Discord Bot 24/7

on:
  workflow_dispatch:  # Manual trigger
  push:               # Run on code changes
    branches: [ main ]
  schedule:           # Restart every 5 hours (before 6-hour limit)
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # 5 hours 50 minutes (just under 6 hours)
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pymongo>=4.0.0  # Explicitly install pymongo
        
    - name: Run Discord Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}  # ADD THIS LINE
      run: |
        # Add automatic restart wrapper
        while true; do
          echo "=== Starting bot at $(date) ==="
          python main.py
          EXIT_CODE=$?
          echo "=== Bot stopped with exit code $EXIT_CODE at $(date) ==="
          
          if [ $EXIT_CODE -eq 0 ]; then
            echo "Bot stopped normally, not restarting."
            break
          else
            echo "Bot crashed or was stopped, restarting in 10 seconds..."
            sleep 10
          fi
        done
